# Methode 1 : KNN

In [ ]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import math
from statistics import mode

In [ ]:
# Calcul distance entre 2 points
def get_distance(p,q):
    d=np.sqrt(sum((p-q)**2))
    return d

In [ ]:
# Calcul les distances entre un point et un ensemble des points
def get_distances(p,X):
    D=[get_distance(p,q) for q in X]
    return D

In [ ]:
# Fonction qui determine les k plus proches voisins
def k_plus_proches(k,D):
    # D : Liste des distances entre p et les autres
    index_proches=np.argsort(D)[:k]
    return index_proches

In [ ]:
def prediction_moi(k,p,X,y):
    # p : Represente la personne
    # X : Ensemble des personnes
    # Y : Liste de ce que tes amis sont
    D=get_distances(p,X) # Recupere les distances entre p et tous les autres
    plus_proches=k_plus_proches(k,D) # Recupere les index des k plus proches
    preds=y[plus_proches] # Ce que tes plus proches sont
    vote=mode(preds) # Ce que tu es
    return vote


In [ ]:
def prediction (k,X,Y):
    preds=[prediction_moi(k,X[x,:],X,Y) for x in range (X.shape[0])]
    return preds

In [ ]:
# Importation des données
from sklearn.datasets import load_iris
X,y=load_iris(return_X_y=True)

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
p=X[50,:]
print(p)
q=X[20,:]
print(q)

[7.  3.2 4.7 1.4]
[5.4 3.4 1.7 0.2]


In [ ]:
get_distance(p,q)

3.6110940170535573

In [ ]:
D=get_distances(p,X)

In [ ]:
k=3
k_plus_proches(k,D)

array([50, 52, 86], dtype=int64)

In [ ]:
prediction_moi(k,p,X,y)

1

In [ ]:
predicts=prediction(k,X,y)

In [ ]:
(y-predicts)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

# Evaluation de Modele
# Séparation des données

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=3)

In [ ]:
print(X.shape[0])
print(X_train.shape[0])
print(X_test.shape[0])

150
105
45


# Implementation du Modele

In [ ]:
# Importation du Modele
from sklearn.neighbors import KNeighborsClassifier
# Initialisation du Modele
model_knn=KNeighborsClassifier(n_neighbors=5)
model_knn
# Apprentissage du modele
model_knn.fit(X_train,y_train)
model_knn

KNeighborsClassifier()

# Prediction du Modele

In [ ]:
y_preds_train=model_knn.predict(X_train)

y_preds_test=model_knn.predict(X_test)


In [ ]:
y_preds_train

array([1, 0, 2, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 1, 0, 0, 2, 1, 0, 0, 1,
       2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 2, 1, 2, 1, 2, 0,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 2, 1, 2, 1, 0,
       2, 1, 2, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 2, 1, 2,
       2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 2, 1])

In [ ]:
y_preds_test

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 2, 0, 2, 2,
       2, 1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 2, 1, 2, 1, 0, 0,
       2])

# Calcul du score de Prediction

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
taux_train=accuracy_score(y_train, y_preds_train)
print('le taux de prediction sur le train est', taux_train*100)
taux_test=accuracy_score(y_test, y_preds_test)
print('le taux de prediction sur le test est', taux_test*100)


le taux de prediction sur le train est 98.09523809523809
le taux de prediction sur le test est 95.55555555555556


In [ ]:
confusion_matrix(y_test,y_preds_test)

array([[17,  0,  0],
       [ 0, 12,  2],
       [ 0,  0, 14]], dtype=int64)

In [ ]:
# Test cross validation
for n in [0.2,0.3,0.4,0.5,0.6,0.7]:
    X_train, X_test, Y_train, Y_test=train_test_split(X,y,test_size=n,random_state=34)
    from sklearn.neighbors import KNeighborsClassifier
    model_knn=KNeighborsClassifier(n_neighbors=5)
    model_knn.fit(X_train, Y_train)
    preds=model_knn.predict(X_test)
    taux=accuracy_score(Y_test,preds)
    print('Pour taille de test :{}'.format(n),'accuracy :{}'.format(taux))


Pour taille de test :0.2 accuracy :0.9666666666666667
Pour taille de test :0.3 accuracy :0.9555555555555556
Pour taille de test :0.4 accuracy :0.9833333333333333
Pour taille de test :0.5 accuracy :0.9866666666666667
Pour taille de test :0.6 accuracy :0.9777777777777777
Pour taille de test :0.7 accuracy :0.9333333333333333


# Choix du meilleur modele


In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid=[
    {'n_neighbors':[20,15,5,22,3,7,9,19,24,31,2,8]},
    {'p':[1,2,3,4]}
]
param_grid

[{'n_neighbors': [20, 15, 5, 22, 3, 7, 9, 19, 24, 31, 2, 8]},
 {'p': [1, 2, 3, 4]}]

In [ ]:
model=KNeighborsClassifier()
model=GridSearchCV(
    model, # Model initialise
    param_grid, # Parametres a optimide
    cv=5, # La valeur k dans k-cross validation
    verbose=20
)
model.fit(X_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [45, 105]

In [ ]:
# Best score
model.best_score_

In [ ]:
# Best parametres
model.best_params_

In [ ]:
# Best model
model.best_estimator_

# Exercice


In [ ]:
# 1. Importer les données diabetes
# la variable outcom represente la presence ou absence du diabete chez les patients
# 2. Implementer le meilleur modele avec K plus proches voisins
# 3. Pour implementer un modele de regerssion logistique il faut :
from sklearn.linear_model import LogisticRegression
# Appliquer ce modele sur les données
# 4. Pour implementer le modele Bayesian il faut :
from sklearn.naive_bayes import GaussianNB
# Appliqué sur les données
# 5. Pour implementer la methode support vector machine il faut :
from sklearn.SVC import SVC
# Appliquer sur les données
# Comparer toutes ces methodes

# Régression

In [ ]:
df_prix_maison=pd.read_csv('prix_maison.csv',sep=';')

In [ ]:
df_prix_maison

price  surface  arrondissement
0    1827.0    44.10             1.0
1    1759.0    42.00             1.0
2    1903.0    54.00             1.0
3    1941.0    46.00             1.0
4    1950.0    48.00             1.0
..      ...      ...             ...
821   849.0    36.00            10.0
822   704.0     8.00            10.0
823  1281.0    37.00            10.0
824  1552.0    64.00            10.0
825  1006.0    22.43            10.0

[826 rows x 3 columns]

In [ ]:
df_prix_maison.head

<bound method NDFrame.head of       price  surface  arrondissement
0    1827.0    44.10             1.0
1    1759.0    42.00             1.0
2    1903.0    54.00             1.0
3    1941.0    46.00             1.0
4    1950.0    48.00             1.0
..      ...      ...             ...
821   849.0    36.00            10.0
822   704.0     8.00            10.0
823  1281.0    37.00            10.0
824  1552.0    64.00            10.0
825  1006.0    22.43            10.0

[826 rows x 3 columns]>

In [ ]:
Y=df_prix_maison['price']
X=df_prix_maison.drop(['price'],axis=1)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3, random_state=34)

In [ ]:
X_train

surface  arrondissement
384    64.00             3.0
692    38.00            10.0
420    67.00             3.0
266    37.00             2.0
752    48.50            10.0
..       ...             ...
85     33.00             1.0
758    48.74            10.0
490    92.00             4.0
122   238.00             1.0
417    29.00             3.0

[578 rows x 2 columns]

In [ ]:
df_prix_maison.isna().sum()

price             1
surface           4
arrondissement    4
dtype: int64

In [ ]:
df_prix_maison.isnull().sum()

price             1
surface           4
arrondissement    4
dtype: int64

In [ ]:
df_prix_maison['price']=df_prix_maison['price'].fillna(df_prix_maison['price'].mean())
df_prix_maison['surface']=df_prix_maison['surface'].fillna(df_prix_maison['surface'].mean())
df_prix_maison['arrondissement']=df_prix_maison['arrondissement'].fillna(df_prix_maison['arrondissement'].mean())

In [ ]:
df_prix_maison.isna().sum()

price             0
surface           0
arrondissement    0
dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression ()
model.fit(X_train,Y_train)
prix_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
mse = mean_squared_error(Y_test,prix_pred)
mse
mae = mean_absolute_error(Y_test,prix_pred)
R = r2_score(Y_test,prix_pred)

In [ ]:
print('le MSE est{}'.format(mse))
print('le MAE est{}'.format(mae))
print('le R carrée est{}'.format(R))

le MSE est0.05090380022014324
le MAE est0.17922633550800562
le R carrée est0.7765048014658846


In [ ]:
# Coefficient estimer du modele
model.coef_

array([ 1.39581556, -0.02317598, -1.04609347, -0.29388356, -0.00347727,
        0.1620788 , -0.0703953 , -0.027618  ,  0.01637587, -0.01745472,
       -0.06190344, -0.01643639,  0.04985771, -0.03112087, -0.06585875,
        0.01439585,  0.12527931, -0.08697537,  0.01400499,  0.03489228,
       -1.21041885, -0.03407675,  0.20020979,  0.74831716,  0.02597682,
        0.01933555, -0.13973401, -0.05188133, -0.06968801, -0.05521568])

In [ ]:
model.intercept_

0.626189346696659

# Arbre de décision

In [ ]:
from sklearn.datasets import load_breast_cancer
X,Y=load_breast_cancer(return_X_y=True)

In [ ]:
from sklearn.preprocessing import StandardScaler
X_cr=StandardScaler().fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X_cr,Y,test_size=0.3,random_state=34)

In [ ]:
# Modele arbre de classification

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=5,min_samples_leaf=7,max_features=5)
model.fit(X_train,Y_train)
pred_cancer=model.predict(X_test)
pred_cancer_prob=model.predict_proba(X_test)

In [ ]:
pred_cancer

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
pred_cancer_prob

array([[0.25      , 0.75      ],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.36363636, 0.63636364],
       [1.        , 0.        ],
       [0.25      , 0.75      ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [0.25      , 0.75      ],
       [0.25      , 0.75      ],
       [0.        , 1.        ],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.71428571, 0.28571429],
       [1.        , 0.        ],
       [0.00552486, 0.99447514],
       [0.00552486, 0.99447514],
       [0.

In [ ]:
from sklearn.metrics import accuracy_score
print('le score du modele est{}'.format(accuracy_score(Y_test,pred_cancer)))

le score du modele est0.9239766081871345


In [ ]:
from sklearn.metrics import accuracy_score
print('le score du modele est{}'.format(accuracy_score(Y_test,pred_cancer)*100))

le score du modele est92.39766081871345


In [ ]:
# Interpretation
importances=model.feature_importances_

In [ ]:
#ranger les variables par odres d'importance
import numpy as np
indice=np.argsort(importances)
noms_var=X.columns
noms_var
num_var=len(importances)
import matplotlib.pyplot as plt
plt.figure()
plt.bar(range(num_var),[noms_var[i] for i in indice], rotation='90')
plt.xlim([-1,num_var])

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

# Forets aleatoires

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_f = RandomForestClassifier(n_estimators=100).fit(X_train,Y_train)
pred_cancer_f= model_f.predict(X_test)
print('le score est:{}'.format(accuracy_score(Y_test,pred_cancer_f)*100))

le score est:97.07602339181285


In [ ]:
importances = model_feature_importances_
import numpy as np
indice=np.argsort(importances)
noms_var=X.columns
noms_var
num_var=len(importances)
import matplotlib.pyplot as plt
plt.figure()
plt.bar(range(num_var),importances[indice])
plt.bar(range(num_var),[noms_var[i] for i in indice], rotation='90')
plt.xlim([-1,num_var])

NameError: name 'model_feature_importances_' is not defined

In [ ]:
X

In [ ]:
Y

In [ ]:
from sklearn.datasets import load_breast_cancer
X,Y=load_breast_cancer(return_X_y=True, as_frame=True)

In [ ]:
X

In [ ]:
Y

In [ ]:
!pip install streamlit

  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13478 sha256=4b5a06148ec9bc31fbe3d083dff403db4f425f2fd28bfbd220910f01657532b9
  Stored in directory: c:\users\lbc\appdata\local\pip\cache\wheels\50\93\f8\4f0a42a03a06626d675f13907b6982ad5ecff383530af5a900
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19582 sha256=34edd1550fee919e7dfaca7d1170a3dd123afe1576fe1ff9c4ba8bddeb720363
  Stored in directory: c:\users\lbc\appdata\local\pip\cache\wheels\2d\f0\a8\1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built blinker validators


In [ ]:
import streamlit

2022-06-15 23:26:39.827 INFO    numexpr.utils: NumExpr defaulting to 4 threads.


In [ ]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle
